# Multi-AI File Paster - Professional Funding & Sponsorship Configuration
#
# Project: Multi-AI File Paster Chrome Extension
# Repository: https://github.com/JosephMatino/MultiAiFilePaster
# Company: WekTurbo Designs - Hostwek LTD
# Website: https://hostwek.com/wekturbo
#
# Development Team:
# • CTO & Lead Developer: Joseph Matino (@JosephMatino)
# • CEO & Scrum Master: Majok Deng (@Majok-Deng)
#
# This extension provides professional file attachment automation across
# ChatGPT, Claude, Gemini, DeepSeek, and Grok AI platforms with privacy-first
# on-device processing and smart language detection for 20+ file formats.

# =============================================================================
# PRIMARY FUNDING CHANNELS
# =============================================================================

# GitHub Sponsors - Primary development funding
github: JosephMatino

# Custom funding platforms and enterprise partnerships
# custom:
#   - "https://hostwek.com/sponsor"
#   - "https://josephmatino.com/support"
#   - "https://majokdeng.com/sponsor"

# =============================================================================
# ENTERPRISE & BUSINESS PARTNERSHIPS
# =============================================================================
#
# For enterprise licensing, custom development, or business partnerships:
#
# Business Development: scrum@majokdeng.com (Majok Deng - CEO & Scrum Master)
# Technical Integration: dev@josephmatino.com (Joseph Matino - CTO & Lead Developer)
# General Support: wekturbo@hostwek.com
# Company Website: https://hostwek.com/wekturbo
#
# Available Services:
# • Custom AI platform integrations
# • Enterprise deployment and configuration
# • White-label extension development
# • Technical consulting and support
# • Performance optimization and scaling
#
# =============================================================================
# FUNDING IMPACT & TRANSPARENCY
# =============================================================================
#
# Your sponsorship directly supports:
# • Continuous development and feature enhancements
# • Multi-platform compatibility testing and maintenance
# • Security audits and privacy protection measures
# • Community support and documentation improvements
# • Open-source contribution to the AI development ecosystem
#
# All funding is transparently managed through WekTurbo Designs - Hostwek LTD
# with regular updates provided to sponsors on development progress and
# feature roadmap implementation.
#
# =============================================================================
